import {Button, VerticalBox} from "std-widgets.slint";
import {VerticalDividingLine, HorizontalDividingLine} from "../../../../components/ui/dividing_line/dividing_line.slint";

import {TextSpinBox} from "../../../../common/ui/text_spinbox.slint";
import {TextLineEdit} from "../../../../common/ui/text_lineedit.slint";
import {TextComboBox} from "../../../../common/ui/text_combobox.slint";
import {TextTextEdit} from "../../../../common/ui/text_textedit.slint";

Pane := Rectangle {
    TouchArea {
        enabled: true;
    }
}

AlarmCodeEditDialog := Window {
    callback on_ok_clicked;
    callback on_cancel_clicked;

    Pane {
    x: 300px;
    y: 0px;
    width: 400px;
    height: 400px;
    background: white;
    border-width: 2px;
    border-color: grey;
    border-radius: 3px;

    VerticalBox {

        VerticalBox {
            vertical-stretch: 2;

            TextLineEdit {
                text_text: "报警码";
                line_edit_text: "";
            }

            VerticalDividingLine{ value: 30px; }

            TextLineEdit {
                text_text: "报警名称";
                line_edit_text: "";
            }

            VerticalDividingLine{ value: 30px; }

            TextComboBox {
                text: "报警等级";
                enabled: false;
            }

            VerticalDividingLine{ value: 30px; }

            TextSpinBox {
                text: "重复判定(秒)";
                value: 60;
            }

            VerticalDividingLine{ value: 30px; }

            TextTextEdit {
                text: "报警描述";
                edit_text: "";
            }
        }

        HorizontalLayout {
            vertical-stretch: 1;

            padding-right: 30px;
            alignment: end;

            Button {
                text: "确定";
                width: 80px;
                height: 30px;

                clicked => {
                    root.on_ok_clicked()
                }
            }

            HorizontalDividingLine{ value: 30px; }

            Button {
                text: "取消";
                width: 80px;
                height: 30px;

                clicked => {
                    root.on_cancel_clicked()
                }
            }
        }

    } // VerticalBox
    }
}

