import {VerticalBox} from "std-widgets.slint";
import {TableWithNumber} from "../../../common/ui/table_with_number.slint";

import {AddDelUpdate} from "../common/add_del_update.slint";

import {AlarmGroupEditDialog} from "alarm_group_dialogs/edit.slint";

Pane := Rectangle {
    TouchArea {
        enabled: true;
    }
}

AlarmGroupPage := VerticalBox{
    property <[{text: string}]> current_row;

    property <bool> show_edit_dialog: false;

    TableWithNumber {
        rows: [
            {cols: [
                {text: "报警组编号"}, {text: "报警组名称"},
            ]},
            {cols: [
                {text: "FPI_Equip"}, {text: "(报警组)FPI水质归一化仪表"},
            ]},
        ];
        // height: hl1.h - 150px;
        // width: 750px;

        menu_on_clicked(index, t) => {
            root.current_row = self.rows[index].cols;
        }

        menu_items: [{text: "📩 编辑"}, {text: "📩 定义为电控设备"}];
        menu_enabled: true;
    }

    AddDelUpdate {
        add-clicked => {}
        update-clicked => {}
        del-clicked => {}
    }

    if show_edit_dialog: AlarmGroupEditDialog {
        on-ok-clicked => {
            show_edit_dialog = false;
        }
        on-cancel-clicked => {
            show_edit_dialog = false;
        }
    }
}

