import {TabWidget, Button, GroupBox, VerticalBox, HorizontalBox} from "std-widgets.slint";
import {TableWithNumber} from "../common/ui/table_with_number.slint";
import {VerticalDividingLine, HorizontalDividingLine} from "../components/ui/dividing_line/dividing_line.slint";

Pane := Rectangle {
    TouchArea {
        enabled: true;
    }
}

AlarmGroupTag := TableWithNumber {
    rows: [
            {cols: [
                {text: "报警组编号"}, {text: "报警组名称"},
            ]},
            {cols: [
                {text: "FPI_Equip"}, {text: "(报警组)FPI水质归一化仪表"},
            ]},
    ];
    // height: hl1.h - 150px;
    // width: 750px;

    menu_on_clicked(index, t) => {
        root.current_row = self.rows[index].cols;
    }

    menu_items: [{text: "📩 编辑"}, {text: "📩 定义为电控设备"}];
    menu_enabled: true;
}
