import {TabWidget, Button, GroupBox, VerticalBox, HorizontalBox} from "std-widgets.slint";
import {TableWithNumber} from "../../../common/ui/table_with_number.slint";

import {AddDelUpdate} from "../common/add_del_update.slint";

import {AlarmLevelEditDialog} from "alarm_level_dialogs/edit.slint";

AlarmLevelPage := VerticalBox {
    property <[{text: string}]> current_row;

    property <bool> show_edit_dialog: false;

    TableWithNumber {
        rows: [
            {cols: [
                {text: "报警等级编号"}, {text: "报警等级命名"}, {text: "报警等级值"}
            ]},
            {cols: [
                {text: "1"}, {text: "故障"}, {text: "1"}
            ]},
        ];
        // height: hl1.h - 150px;
        // width: 750px;

        menu_on_clicked(index, t) => {
            root.current_row = self.rows[index].cols;
        }

        menu_items: [{text: "📩 编辑"}, {text: "📩 定义为电控设备"}];
        menu_enabled: true;
    }

    AddDelUpdate {
        add-clicked => {}
        update-clicked => {}
        del-clicked => {}
    }

    if show_edit_dialog: AlarmLevelEditDialog {
        on-ok-clicked => {
            show_edit_dialog = false;
        }
        on-cancel-clicked => {
            show_edit_dialog = false;
        }
    }
}
