import {
    HorizontalBox, ComboBox
} from "std-widgets.slint";

TextComboBox := HorizontalBox {
    property <string> text;
    property <[string]> model;
    property <bool> enabled;

    callback selected(string);

    t := Text {
        horizontal-stretch: 1;
        text: root.text;
    }

    ComboBox {
        // height: t.height;
        horizontal-stretch: root.model.length;
        model: root.model;
        current-index: 0;
        enabled <=> root.enabled;
        selected(v) => { root.selected(v) }
    }
}


