import {
    HorizontalBox, SpinBox
} from "std-widgets.slint";

TextSpinBox := HorizontalBox {
    property <string> text;
    property <bool> enabled;
    callback set_enabled(bool);
    set_enabled(enabled) => {
        // t.enabled = enabled;
        sb.enabled = enabled;
    }

    t := Text {
        text: root.text;
    }

    sb := SpinBox {
        value: 0;
        minimum: 0;
        maximum: 100;
    }
}

