import {Button, VerticalBox, ScrollView} from "std-widgets.slint";
import {VerticalDividingLine, HorizontalDividingLine} from "../../../../components/ui/dividing_line/dividing_line.slint";

import {TextSpinBox} from "../../../../common/ui/text_spinbox.slint";
import {TextLineEdit} from "../../../../common/ui/text_lineedit.slint";
import {TextComboBox} from "../../../../common/ui/text_combobox.slint";
import {TextTextEdit} from "../../../../common/ui/text_textedit.slint";

import {OkCancel} from "../../common/ok_cancel.slint";

Pane := Rectangle {
    TouchArea {
        enabled: true;
    }
}

AlarmGroupEditDialog := Window {
    callback on-ok-clicked;
    callback on-cancel-clicked;

    ScrollView {
    x: 100px;
    y: 200px;
    width: 600px;
    height: 400px;
    background: white;
    border-width: 2px;
    border-color: grey;
    border-radius: 3px;

    VerticalBox {

        VerticalBox {
            vertical-stretch: 1;

            TextLineEdit {
                text_text: "报警组编号";
                line_edit_text: "";
            }

            TextLineEdit {
                text_text: "报警组名称";
                line_edit_text: "";
            }
        }

        OkCancel {
            ok-clicked => { root.on-ok-clicked(); }
            cancel-clicked => { root.on-cancel-clicked(); }
        }

    } // VerticalBox
    }
}

