import {TabWidget, Button, GroupBox, VerticalBox, HorizontalBox} from "std-widgets.slint";
import {TableWithNumber} from "../common/ui/table_with_number.slint";
import {VerticalDividingLine, HorizontalDividingLine} from "../components/ui/dividing_line/dividing_line.slint";

Pane := Rectangle {
    TouchArea {
        enabled: true;
    }
}

AlarmDialog := Window {
    callback on_ok_clicked;
    callback on_cancel_clicked;

    // private
    property <bool> show_edit_dialog: false;
    property <[{text: string}]> current_row;

    Pane {
    x: 100px;
    y: 0px;
    width: 800px;
    height: 800px;
    background: white;
    border-width: 2px;
    border-color: grey;
    border-radius: 3px;

    VerticalBox {

        TableWithNumber {
            vertical-stretch: 1;

            rows: [
                  {cols: [
                      {text: "报警组编号"}, {text: "报警组名称"},
                  ]},
                  {cols: [
                      {text: "FPI_Equip"}, {text: "(报警组)FPI水质归一化仪表"},
                  ]},
            ];
            // height: hl1.h - 150px;
            // width: 750px;

            menu_on_clicked(index, t) => {
                root.current_row = self.rows[index].cols;
            }

            menu_items: [{text: "📩 编辑"}, {text: "📩 定义为电控设备"}];
            menu_enabled: true;
        }

        VerticalDividingLine{ value: 30px; }

        HorizontalLayout {
            vertical-stretch: 1;

            padding-right: 30px;
            alignment: end;

            Button {
                text: "启动";
                width: 80px;
                height: 30px;

                clicked => {
                    root.on_ok_clicked()
                }
            }

            HorizontalDividingLine{ value: 30px; }

            Button {
                text: "停止";
                width: 80px;
                height: 30px;

                clicked => {
                    root.on_cancel_clicked()
                }
            }

            HorizontalDividingLine{ value: 30px; }

            Button {
                text: "编辑";
                width: 80px;
                height: 30px;

                clicked => {
                    show_edit_dialog = true;
                }
            }

            HorizontalDividingLine{ value: 30px; }

            Button {
                text: "关闭";
                width: 80px;
                height: 30px;

                clicked => {
                    root.on_cancel_clicked()
                }
            }
        }

    } // VerticalBox
    }

    if show_edit_dialog: TimerEditDialog {
        on_ok_clicked => {
            show_edit_dialog = false;
        }
        on_cancel_clicked => {
            show_edit_dialog = false;
        }
    }
}
