import {TabWidget, Button, GroupBox, VerticalBox, HorizontalBox} from "std-widgets.slint";
import {TableWithNumber, TableWithNumberRow} from "../../common/ui/table_with_number.slint";

import {AddDelUpdate} from "common/add_del_update.slint";
import { VerticalDividingLine } from "../../components/ui/dividing_line/dividing_line.slint";

Pane := Rectangle {
    TouchArea {
        enabled: true;
    }
}

HistoryDataQueryTag := GroupBox {
    property <[TableWithNumberRow]> left-rows: [
        {cols: [{text: "名称"}, {text: "单位"}, {text: "小数位数"}]},
        {cols: [{text: "采水泵PU1"}, {text: ""}, {text: "2"}]},
        {cols: [{text: "采水泵PU2"}, {text: ""}, {text: "2"}]},
        {cols: [{text: "采水泵PU1"}, {text: ""}, {text: "2"}]},
        {cols: [{text: "采水泵PU1"}, {text: ""}, {text: "2"}]},
    ];

    callback to-single-right-clicked();
    callback to-single-left-clicked();
    callback to-multi-right-clicked();
    callback to-multi-left-clicked();

    HorizontalBox {
        TableWithNumber {
            vertical-stretch: 6;

            rows: left-rows;

            // rows: [
            //       {cols: [{text: "名称"}, {text: "单位"}, {text: "小数位数"}]},
            //       {cols: [{text: "采水泵PU1"}, {text: ""}, {text: "2"}]},
            //       {cols: [{text: "采水泵PU2"}, {text: ""}, {text: "2"}]},
            //       {cols: [{text: "采水泵PU1"}, {text: ""}, {text: "2"}]},
            //       {cols: [{text: "采水泵PU1"}, {text: ""}, {text: "2"}]},
            // ];

            // menu_items: [{text: "📩 编辑"}];
            menu_enabled: true;
        }

        VerticalBox {
            Button {
                text: ">";
                clicked => { root.to-single-right-clicked() }
            }
            Button {
                text: "<";
                clicked => { root.to-single-left-clicked() }
            }

            VerticalDividingLine {
            }

            Button {
                text: ">>";
                clicked => { root.to-multi-right-clicked() }
            }
            Button {
                text: "<<";
                clicked => { root.to-multi-left-clicked() }
            }
        }

        TableWithNumber {
            vertical-stretch: 6;

            rows: [
                  {cols: [{text: "名称"}, {text: "单位"}, {text: "小数位数"}]},
                  {cols: [{text: "总磷"}, {text: "mg/l"}, {text: "2"}]},
                  {cols: [{text: "压力"}, {text: "KPa"}, {text: "2"}]},
                  {cols: [{text: "湿度"}, {text: "%"}, {text: "2"}]},
                  {cols: [{text: "氨氮"}, {text: "。C"}, {text: "2"}]},
            ];

            // menu_items: [{text: "📩 编辑"}];
            menu_enabled: true;
        }
    }
}

DataQueryAndTableReportDialog := Window {
    callback on_ok_clicked;
    callback on_cancel_clicked;

    callback to-single-right-clicked();
    callback to-single-left-clicked();
    callback to-multi-right-clicked();
    callback to-multi-left-clicked();

    property <[TableWithNumberRow]> left-rows;

    // private
    property <bool> show-add-group-dialog: false;

    Pane {
        x: 100px;
        y: 0px;
        width: 800px;
        height: 800px;
        background: white;
        border-width: 2px;
        border-color: grey;
        border-radius: 3px;

        TabWidget {
            Tab {
                title: "历史数据查询";

                HistoryDataQueryTag {
                    left-rows <=> root.left-rows;
                }
            }
        }
    }

    AddDelUpdate {
        add-clicked => {
        }
        del-clicked => {
        }
        update-clicked => {
        }
    }

    // if show-add-group-dialog: OperatorEditDialog {
    //     on_ok_clicked => {
    //         show_operator_edit_dialog = false;
    //     }
    //     on_cancel_clicked => {
    //         show_operator_edit_dialog = false;
    //     }
    // }
}

