import {TabWidget, Button, GroupBox, VerticalBox, HorizontalBox} from "std-widgets.slint";
import {TableWithNumber} from "../../common/ui/table_with_number.slint";

import {AddDelUpdate} from "common/add_del_update.slint";

Pane := Rectangle {
    TouchArea {
        enabled: true;
    }
}

HistoryDataQueryTag := GroupBox {
    HorizontalBox {
        TableWithNumber {
            vertical-stretch: 6;

            rows: [
                  {cols: [{text: "名称"}, {text: "单位"}, {text: "小数位数"}]},
                  {cols: [{text: "采水泵PU1"}, {text: ""}, {text: "2"}]},
                  {cols: [{text: "采水泵PU2"}, {text: ""}, {text: "2"}]},
                  {cols: [{text: "采水泵PU1"}, {text: ""}, {text: "2"}]},
                  {cols: [{text: "采水泵PU1"}, {text: ""}, {text: "2"}]},
            ];

            // menu_items: [{text: "📩 编辑"}];
            menu_enabled: true;
        }
    }
}

DataQueryAndTableReportDialog := Window {
    callback on_ok_clicked;
    callback on_cancel_clicked;

    // private
    property <bool> show-add-group-dialog: false;

    Pane {
        x: 100px;
        y: 0px;
        width: 800px;
        height: 800px;
        background: white;
        border-width: 2px;
        border-color: grey;
        border-radius: 3px;

        TabWidget {
            Tab {
                title: "历史数据查询";

                HistoryDataQueryTag {
                }
            }
        }
    }

    AddDelUpdate {
        add-clicked => {
        }
        del-clicked => {
        }
        update-clicked => {
        }
    }

    if show-add-group-dialog: OperatorEditDialog {
        on_ok_clicked => {
            show_operator_edit_dialog = false;
        }
        on_cancel_clicked => {
            show_operator_edit_dialog = false;
        }
    }
}

