import {TabWidget, Button, GroupBox, VerticalBox, HorizontalBox} from "std-widgets.slint";
import {TableWithNumber} from "../../common/ui/table_with_number.slint";
import {VerticalDividingLine, HorizontalDividingLine} from "../../components/ui/dividing_line/dividing_line.slint";

import {AlarmGroupPage} from "alarm_tags/alarm_group.slint";
import {AlarmCodePage} from "alarm_tags/alarm_code.slint";
import {AlarmLevelPage} from "alarm_tags/alarm_level.slint";
import {AlarmSourcePage} from "alarm_tags/alarm_source.slint";

import {OperatorEditDialog} from "systask_tags/operator_edit.slint";

Pane := Rectangle {
    TouchArea {
        enabled: true;
    }
}

DataQueryAndTableReportDialog := Window {
    property <string> device_no;
    property <string> device_name;
    property <string> device_address;
    property <string> device_alarm_group_no;
    property <string> device_alarm_source_no;
    property <string> device_type_desc;

    callback on_ok_clicked;
    callback on_cancel_clicked;

    // private
    property <bool> show_operator_edit_dialog: false;
    property <int> tag_current_index: 0;
    property <[{text: string}]> current_row;
    property <string> current_op;

    Pane {
    x: 100px;
    y: 0px;
    width: 800px;
    height: 800px;
    background: white;
    border-width: 2px;
    border-color: grey;
    border-radius: 3px;

    TabWidget {
        Tab {
            title: "基本项";

            BasicEntries {
            }
        }

        Tab {
            title: "扩展项";
        }
    }
    }

    if show_operator_edit_dialog: OperatorEditDialog {
        on_ok_clicked => {
            show_operator_edit_dialog = false;
        }
        on_cancel_clicked => {
            show_operator_edit_dialog = false;
        }
    }
}

