import {
    LineEdit, ComboBox, TabWidget, Button,
    GroupBox, VerticalBox, HorizontalBox, SpinBox,
    TextEdit
} from "std-widgets.slint";
import {VerticalDividingLine, HorizontalDividingLine} from "../components/ui/dividing_line/dividing_line.slint";
// import {BasicEntries} from "./device_edit_dialogs/.slint";
import {TextSpinBox} from "../common/ui/text_spinbox.slint";
import {TextLineEdit} from "../common/ui/text_lineedit.slint";
import {TextComboBox} from "../common/ui/text_combobox.slint";

Pane := Rectangle {
    TouchArea {
        enabled: true;
    }
}

export DeviceEditDialog := Window {
    property <string> device_no;
    property <string> device_name;
    property <string> device_alarm_group_no;

    callback on_ok_clicked;
    callback on_cancel_clicked;

    Pane {
    x: 200px;
    y: 0px;
    width: 600px;
    height: 800px;
    background: white;
    border-width: 2px;
    border-color: grey;
    border-radius: 3px;

    VerticalBox {
    // VerticalLayout {
        max-height: parent.height;

        GroupBox {
            vertical-stretch: 2;
            title: "设备基本信息";

            // VerticalBox {
            VerticalLayout {
                TextComboBox {
                    text: "设备实现类选择";
                    model: ["1.dll", "2.dll", "3.dll"];
                }

                // HorizontalBox {
                HorizontalLayout {
                    // HorizontalBox {
                    TextLineEdit {
                        text_text: "设备编号";
                        line_edit_text: root.device_no;
                    }
                    TextLineEdit {
                        text_text: "设备名称";
                        line_edit_text: root.device_name;
                    }
                }
            }
        }

        HorizontalLayout {
            vertical-stretch: 5;

            GroupBox {
                title: "设备通道配置";

                VerticalLayout {
                    TextSpinBox {
                        text: "数值输入通道";
                    }
                    TextSpinBox {
                        text: "数值输出通道";
                    }
                    TextSpinBox {
                        text: "开关量输入通道";
                    }
                    TextSpinBox {
                        text: "开关量输出通道";
                    }
                }
            }

            GroupBox {
                title: "设备报警相关配置";

                VerticalLayout {
                    TextLineEdit {
                        text_text: "设备报警组编号";
                        line_edit_text: root.device_alarm_group_no;
                    }
                }
            }
        }

        GroupBox {
            vertical-stretch: 3;
            title: "设备通道详细配置";

            HorizontalLayout {
                Button {
                    text: "数值输入通道";
                }
                Button {
                    text: "数值输出通道";
                    enabled: false;
                }
                Button {
                    text: "开关量输入通道";
                }
                Button {
                    text: "开关量输出通道";
                    enabled: false;
                }
            }
        }

        GroupBox {
            vertical-stretch: 2;
            title: "设备通信默认参数配置";

            VerticalLayout {
                HorizontalLayout {
                    TextComboBox {
                        text: "通信类型选择";
                        model: ["COM1"];
                    }
                }
                HorizontalLayout {
                    TextComboBox {
                        text: "串口号";
                        model: [];
                    }
                }
                HorizontalLayout {
                    Text {
                        text: "数据位";
                    }
                }
            }
        }

        GroupBox {
            vertical-stretch: 2;
            title: "设备描述信息";

            TextEdit {
            }
        }

        HorizontalLayout {
            vertical-stretch: 1;

            padding-right: 30px;
            alignment: end;

            Button {
                text: "确定";
                // width: 80px;
                // height: 30px;

                clicked => {
                    root.on_ok_clicked()
                }
            }

            HorizontalDividingLine{ value: 30px; }

            Button {
                text: "取消";
                // width: 80px;
                // height: 30px;

                clicked => {
                    root.on_cancel_clicked()
                }
            }
        }
    }
    }
}

