import {Button} from "std-widgets.slint";

FirstPage := Rectangle {
    width: 500px;
    height: 500px;

    visible: true;

    VerticalLayout {
        Rectangle {
            width: 300px;
            height: 300px;
        }

        HorizontalLayout {
            Button {
                text: "下一步";
            }
            Button {
                text: "退出";
            }
        }
    }
}

Main := Window {
    first_page := FirstPage {}
}

