import {Button, GroupBox, VerticalBox, HorizontalBox} from "std-widgets.slint";
import {ListContainingCheckbox} from "../common/ui/list_containing_checkbox.slint";
import {VerticalDividingLine} from "../components/ui/dividing_line/dividing_line.slint";

MeasurementFactorsPage := VerticalLayout {
    visible: true;

    property <length> ph;
    property <length> pw;

    hl1 := HorizontalBox {
        property <length> h: 720px;

        Image {
            width: 250px;
            // width: length(root.pw/4);
            height: parent.h;
            source: @image-url("images/config1.png");
        }

        GroupBox {
            title: "测量因子配置";

            VerticalLayout {
                VerticalLayout {
                    vertical-stretch: 15;

                    ListContainingCheckbox {
                        rows: [
                              {text: "水温"},
                              {text: "pH值"},
                              {text: "硫酸盐"},
                              {text: "氯化物"},
                              {text: "硝酸盐"},
                              {text: "氨氮"},
                              {text: "总磷"},
                              {text: "高锰酸钾指数"},
                              {text: "溶解氧"},
                              {text: "化学需氧量"},
                              {text: "生化需氧量"},
                              {text: "氟化物"},
                              {text: "硒"},
                              {text: "砷"},
                              {text: "六价铬"},
                              {text: "氰化物"},
                              {text: "挥发酚"},
                              {text: "石油类"},
                              {text: "总铁"},
                              {text: "锰"},
                              {text: "镉"},
                        ];
                        // height: hl1.h - 150px;
                        // width: 750px;
                    }
                }

                VerticalLayout {
                    vertical-stretch: 1;

                    VerticalDividingLine{ value: 2px; }
                }

                VerticalLayout {
                    vertical-stretch: 1;

                    Text {
                        font-size: 20px;
                        color: blue;
                        text: "提示: 右键可编辑测量项";
                    }
                }
            }
        }
    }

    HorizontalLayout {
        padding-top: 30px;
        padding-right: 30px;
        alignment: end;

        Button {
            text: "上一步(P)";
            width: 80px;
            height: 30px;
        }

        Rectangle {
            width: 30px;
        }

        Button {
            text: "下一步";
            width: 80px;
            height: 30px;
        }

        Rectangle {
            width: 30px;
        }

        Button {
            text: "退出(C)";
            width: 80px;
            height: 30px;
        }
    }
}

