import {Button} from "std-widgets.slint";

MeasurementFactorsPage := VerticalLayout {
    visible: true;

    property <length> ph;
    property <length> pw;

    HorizontalLayout {
        property <length> h: 720px;

        Image {
            width: 250px;
            // width: length(root.pw/4);
            height: parent.h;
            source: @image-url("images/config1.png");
        }

        Image {
            width: 750px;
            height: parent.h;
            source: @image-url("images/config1-right.png");
        }
    }

    HorizontalLayout {
        padding-top: 30px;
        padding-right: 30px;
        alignment: end;

        Button {
            text: "下一步";
            width: 80px;
            height: 30px;
        }

        Rectangle {
            width: 30px;
        }

        Button {
            text: "退出(C)";
            width: 80px;
            height: 30px;
        }
    }
}

