import {TabWidget, Button, GroupBox, VerticalBox, HorizontalBox} from "std-widgets.slint";
import {TableWithNumber} from "../common/ui/table_with_number.slint";
import {ListContainingCheckbox} from "../common/ui/list_containing_checkbox.slint";
import {VerticalDividingLine, HorizontalDividingLine} from "../components/ui/dividing_line/dividing_line.slint";
import {DeviceEditDialog} from "device_edit.slint";
import {TextLineEdit} from "../common/ui/text_lineedit.slint";

SerialPortPage := VerticalLayout {
    property <length> ph;
    property <length> pw;

    property <string> port_no;
    property <string> baud_rate;

    callback prev_clicked;
    callback next_clicked;

    // private variants
    property <bool> show_edit_dialog: true;

    hl1 := HorizontalBox {
        property <length> h: 720px;

        Image {
            width: 250px;
            // width: length(root.pw/4);
            height: parent.h;
            source: @image-url("images/config1.png");
        }

        GroupBox {
            title: "串口配置";

            VerticalBox {
                ListContainingCheckbox {
                    vertical-stretch: 2;

                    rows: [
                          {text: "采水泵PU2"},
                          {text: "采水泵PU2"},
                          {text: "清水泵PU1"},
                          {text: "沉淀池后增压泵PU3"},
                          {text: "隔膜泵PU2"},
                          {text: "内管路清洗"},
                    ];
                    // height: hl1.h - 150px;
                    // width: 750px;

                    menu_on_clicked(index, t) => {
                        show_edit_dialog = true;
                    }

                    menu_enabled: true;
                }

                TableWithNumber {
                    vertical-stretch: 2;

                    rows: [
                          {cols: [{text: "序号"}, {text: "设备名称"}]},
                          {cols: [{text: "1"}, {text: "和利时PLC_2012版本"}]},
                    ];
                    // height: hl1.h - 150px;
                    // width: 750px;

                    menu_on_clicked(index, t) => {
                        show_edit_dialog = true;
                    }

                    menu_items: [{text: "📩 编辑"}, {text: "📩 定义为电控设备"}];
                    menu_enabled: true;
                }

                GroupBox {
                    vertical-stretch: 1;

                    title: "详细配置";

                    HorizontalBox {
                        port_no_edit := TextLineEdit {
                            text_text: "端口号";
                            line_edit_text: root.port_no;
                        }
                        baud_rate_edit := TextLineEdit {
                            text_text: "波特率";
                            line_edit_text: root.baud_rate;
                        }
                        setting_button := Button {
                            text: "设置";
                        }
                    }
                }
            }
        }
    }

    HorizontalLayout {
        padding-right: 30px;
        alignment: end;

        Button {
            text: "上一步(P)";
            width: 80px;
            height: 30px;

            clicked => {
                root.prev_clicked()
            }
        }

        HorizontalDividingLine{ value: 30px; }

        Button {
            text: "下一步";
            width: 80px;
            height: 30px;

            clicked => {
                root.next_clicked()
            }
        }

        HorizontalDividingLine{ value: 30px; }

        Button {
            text: "退出(C)";
            width: 80px;
            height: 30px;
        }
    }
}


