import {TabWidget, Button, GroupBox, VerticalBox, HorizontalBox} from "std-widgets.slint";
import {TableWithNumber} from "../common/ui/table_with_number.slint";
import {VerticalDividingLine, HorizontalDividingLine} from "../components/ui/dividing_line/dividing_line.slint";

import {AtomicPage} from "systask_tags/atomic.slint";
import {ProcessPage} from "systask_tags/process.slint";
import {SysModePage} from "systask_tags/sysmode.slint";

import {OperatorEditDialog} from "systask_tags/operator_edit.slint";

Pane := Rectangle {
    TouchArea {
        enabled: true;
    }
}

SysTaskDialog := Window {
    property <string> device_no;
    property <string> device_name;
    property <string> device_address;
    property <string> device_alarm_group_no;
    property <string> device_alarm_source_no;
    property <string> device_type_desc;

    callback on_ok_clicked;
    callback on_cancel_clicked;

    // private
    property <bool> show_operator_edit_dialog: false;
    property <int> tag_current_index: 0;

    Pane {
    x: 100px;
    y: 0px;
    width: 800px;
    height: 800px;
    background: white;
    border-width: 2px;
    border-color: grey;
    border-radius: 3px;

    VerticalBox {

        tw := TabWidget {
            Tab {
                title: "原子操作";

                AtomicPage {
                }
            }
            Tab {
                title: "流程操作";

                ProcessPage {
                }
            }
            Tab {
                title: "系统模式操作";

                SysModePage {
                }
            }
        }

        HorizontalLayout {
            vertical-stretch: 1;

            padding-right: 30px;
            alignment: end;

            Button {
                text: "新增";
                width: 80px;
                height: 30px;

                clicked => {
                    root.tag_current_index = tw.current-index;
                    root.show_operator_edit_dialog = true;
                }
            }

            HorizontalDividingLine{ value: 30px; }

            Button {
                text: "修改";
                width: 80px;
                height: 30px;

                clicked => {
                    root.on_ok_clicked()
                }
            }

            HorizontalDividingLine{ value: 30px; }

            Button {
                text: "删除";
                width: 80px;
                height: 30px;

                clicked => {
                    root.on_cancel_clicked()
                }
            }
        }

        VerticalDividingLine{ value: 30px; }

        HorizontalLayout {
            vertical-stretch: 1;

            padding-right: 30px;
            alignment: end;

            Button {
                text: "确定";
                width: 80px;
                height: 30px;

                clicked => {
                    root.on_ok_clicked()
                }
            }

            HorizontalDividingLine{ value: 30px; }

            Button {
                text: "取消";
                width: 80px;
                height: 30px;

                clicked => {
                    root.on_cancel_clicked()
                }
            }
        }

    } // VerticalBox
    }

    if show_operator_edit_dialog: OperatorEditDialog {
        on_ok_clicked => {
            show_operator_edit_dialog = false;
        }
        on_cancel_clicked => {
            show_operator_edit_dialog = false;
        }
    }
}

