import {TabWidget, Button, TextEdit, CheckBox, GroupBox, VerticalBox, HorizontalBox} from "std-widgets.slint";
import {TableWithNumber} from "../../../common/ui/table_with_number.slint";
import {VerticalDividingLine, HorizontalDividingLine} from "../../../components/ui/dividing_line/dividing_line.slint";

import {TextSpinBox} from "../../../common/ui/text_spinbox.slint";
import {TextLineEdit} from "../../../common/ui/text_lineedit.slint";
import {TextComboBox} from "../../../common/ui/text_combobox.slint";
import {TextTextEdit} from "../../../common/ui/text_textedit.slint";
import {CheckBoxGroupBox} from "../../../common/ui/checkbox_groupbox.slint";

Pane := Rectangle {
    TouchArea {
        enabled: true;
    }
}

TimerEditDialog := Window {
    property <string> operate_no;
    property <string> operate_name;
    property <string> resulting_state;
    property <string> competitive_resource;

    callback on_ok_clicked;
    callback on_cancel_clicked;

    // private
    property <bool> show_timer_dialog: false;

    Pane {
    x: 200px;
    y: 50px;
    width: 600px;
    height: 700px;
    background: white;
    border-width: 2px;
    border-color: grey;
    border-radius: 3px;

    VerticalBox {
        HorizontalBox {
            GroupBox {
                title: "定时器基本配置";

                VerticalBox {
                    TextSpinBox {
                        text: "优先级";
                        value: 10;
                    }
                    TextSpinBox {
                        text: "任务重量";
                        value: 10;
                    }
                    TextSpinBox {
                        text: "最多并行";
                        value: 10;
                    }
                    TextComboBox {
                        text: "关联设备";
                        enabled: false;
                    }
                    TextTextEdit {
                        text: "定时器描述";
                        edit_text: "";
                    }
                }
            }

            GroupBox {
                title: "定时器运行模式";

                VerticalBox {
                    CheckBoxGroupBox {
                        text: "周期性任务";

                        GroupBox {
                            title: "周期模式选项";

                            VerticalBox {
                                TextSpinBox {
                                    text: "周期(秒)";
                                    value: 15;
                                }
                                CheckBox {
                                    text: "启用定时器";
                                }
                                CheckBox {
                                    text: "立即触发定时任务";
                                }
                            }
                        }
                    }
                    CheckBoxGroupBox {
                        text: "定点任务";

                        GroupBox {
                            title: "定点模式选项";

                            VerticalBox {
                                TextComboBox {
                                    text: "定点模式";
                                    model: ["月模式"];
                                }
                                TextSpinBox {
                                    text: "定点精度(秒)";
                                    value: 3;
                                }
                                Button {
                                    text: "定点计划";
                                }
                            }
                        }
                    }
                }
            }
        }

        HorizontalLayout {
            vertical-stretch: 1;

            padding-right: 30px;
            alignment: end;

            Button {
                text: "确定";
                width: 80px;
                height: 30px;

                clicked => {
                    root.on_ok_clicked()
                }
            }

            HorizontalDividingLine{ value: 30px; }

            Button {
                text: "取消";
                width: 80px;
                height: 30px;

                clicked => {
                    root.on_cancel_clicked()
                }
            }
        }

    } // VerticalBox
    }

    // if show_timer_dialog: TimerDialog {
    //     on_ok_clicked => {
    //         show_timer_dialog = false;
    //     }
    //     on_cancel_clicked => {
    //         show_timer_dialog = false;
    //     }
    // }
}



