import {Button, VerticalBox} from "std-widgets.slint";
import {VerticalDividingLine, HorizontalDividingLine} from "../../../../components/ui/dividing_line/dividing_line.slint";

import {TextLineEdit} from "../../../../common/ui/text_lineedit.slint";
import {TextSpinBox} from "../../../../common/ui/text_spinbox.slint";
import {TextComboBox} from "../../../../common/ui/text_combobox.slint";

import {OkCancel} from "../../common/ok_cancel.slint";

Pane := Rectangle {
    TouchArea {
        enabled: true;
    }
}

AlarmSourceEditDialog := Window {
    callback on_ok_clicked;
    callback on_cancel_clicked;

    Pane {
    x: 300px;
    y: 0px;
    width: 400px;
    height: 400px;
    background: white;
    border-width: 2px;
    border-color: grey;
    border-radius: 3px;

    VerticalBox {

        VerticalBox {
            vertical-stretch: 2;

            TextLineEdit {
                text_text: "报警源编号";
                line_edit_text: "";
            }

            VerticalDividingLine{ value: 30px; }

            TextLineEdit {
                text_text: "报警源名称";
                line_edit_text: "";
            }

            VerticalDividingLine{ value: 30px; }

            TextSpinBox {
                text: "对应报警值";
                enabled: false;
            }
        }

        OkCancel {
            vertical-stretch: 1;

            ok-clicked => { root.on-ok-clicked(); }
            cancel-clicked => { root.on-cancel-clicked(); }
        }
    } // VerticalBox
    }
}

