import { ListView, ScrollView } from "std-widgets.slint";
import { MenuItem, Menu } from "../../ui/menu/menu.slint";
import { MenuArea } from "../../ui/menu/menu_area.slint";

Pane := Rectangle {
    TouchArea {}
}

export struct Col := {
    text: string,
}

export struct Row := {
    // cols: [Col]
    text: string
}

export TableView := Pane {
    width: 500px;
    height: 500px;

    property <int> current_index;
    property <length> item_height: 100px;
    property <[Row]> rows: [{text: "1"}, {text: "2"}, {text: "3"}, {text: "4"}, {text: "5"}, {text: "6"}];
    property <[MenuItem]> menu_items: [{text: "edit"}, {text: "delete"}];
    callback right_click_on_the_view(int, length, length, string);
    callback right_click_view(length, length);
    right_click_view(mx, my) => {
        current_index = my/item_height;
        root.right_click_on_the_view(current_index, mx, my, rows[current_index].text);
    }
    callback menu_on_clicked(int, string);

    lv := ScrollView {
        viewport-height: rows.length * root.item_height;
        // height: 600px;

        for r[index] in rows: Rectangle {
            Rectangle {
                y: index * self.height;
                height: root.item_height;

                Text{
                    text: r.text;
                }
            }

            MenuArea {
                menu_items <=> root.menu_items;
                right_click_view(x, y) => {root.right_click_view(x, y)}
                on_clicked(int, string) => {root.menu_on_clicked(int, string)}
            }
        }
    }
}

