import {
    LineEdit, ComboBox, TabWidget, Button,
    GroupBox, VerticalBox, HorizontalBox, SpinBox,
    TextEdit, CheckBox, GridBox, ScrollView
} from "std-widgets.slint";
import {VerticalDividingLine, HorizontalDividingLine} from "../../../components/ui/dividing_line/dividing_line.slint";
// import {BasicEntries} from "./device_edit_dialogs/.slint";
import {TextSpinBox} from "../../../common/ui/text_spinbox.slint";
import {TextLineEdit} from "../../../common/ui/text_lineedit.slint";
import {TextComboBox} from "../../../common/ui/text_combobox.slint";

import {OkCancel} from "../common/ok_cancel.slint";

Pane := Rectangle {
    TouchArea {
        enabled: true;
    }
}

Item := HorizontalBox {
// Item := Pane {
    property <string> text;
    property <int> index;
    // property <bool> checkbox-enabled;
    property <bool> checkbox-checked;

        // height: (50px * (index + 1)) + 5px;

    CheckBox {
        // text <=> "每月" + root.text + "号";
        text <=> root.text;
        checked <=> checkbox-checked;
        // enabled <=> checkbox-enabled;
    }

    SpinBox {
        value: 0;
        minimum: 0;
        maximum: 1000;
    }
}

Items := Rectangle {
    property <[string]> cols;

    for col[index] in cols: Item {
        text: col;
        width: 150px;
        index: index;
        // height: (50px * (index + 1)) + 5px;
        y: (50px * index) + 5px;
    }
}

export MonthPlanDialog := Window {
    title: "月计划";

    property<string> timer_desc;

    callback on_ok_clicked;
    callback on_cancel_clicked;

    property <bool> all-checked: true;

    ScrollView {
    x: 200px;
    y: 100px;
    width: 600px;
    height: 600px;
    background: white;
    border-width: 2px;
    border-color: grey;
    border-radius: 3px;

    VerticalBox {

        HorizontalBox {
            VerticalBox {
                Item {
                    text: "每月1日";
                    checkbox-checked: root.all-checked;
                }
                Item {
                    text: "每月2日";
                    checkbox-checked: root.all-checked;
                }
                Item {
                    text: "每月3日";
                    checkbox-checked: root.all-checked;
                }
                Item {
                    text: "每月4日";
                    checkbox-checked: root.all-checked;
                }
                Item {
                    text: "每月5日";
                    checkbox-checked: root.all-checked;
                }
                Item {
                    text: "每月6日";
                    checkbox-checked: root.all-checked;
                }
                Item {
                    text: "每月7日";
                    checkbox-checked: root.all-checked;
                }
                Item {
                    text: "每月8日";
                    checkbox-checked: root.all-checked;
                }
                Item {
                    text: "每月9日";
                    checkbox-checked: root.all-checked;
                }
                Item {
                    text: "每月10日";
                    checkbox-checked: root.all-checked;
                }
            }

            VerticalBox {
                Item {
                    text: "每月11日";
                    checkbox-checked: root.all-checked;
                }
                Item {
                    text: "每月12日";
                    checkbox-checked: root.all-checked;
                }
                Item {
                    text: "每月13日";
                    checkbox-checked: root.all-checked;
                }
                Item {
                    text: "每月14日";
                    checkbox-checked: root.all-checked;
                }
                Item {
                    text: "每月15日";
                    checkbox-checked: root.all-checked;
                }
                Item {
                    text: "每月16日";
                    checkbox-checked: root.all-checked;
                }
                Item {
                    text: "每月17日";
                    checkbox-checked: root.all-checked;
                }
                Item {
                    text: "每月18日";
                    checkbox-checked: root.all-checked;
                }
                Item {
                    text: "每月19日";
                    checkbox-checked: root.all-checked;
                }
                Item {
                    text: "每月20日";
                    checkbox-checked: root.all-checked;
                }
            }

            VerticalBox {
                Item {
                    text: "每月21日";
                    checkbox-checked: root.all-checked;
                }
                Item {
                    text: "每月22日";
                    checkbox-checked: root.all-checked;
                }
                Item {
                    text: "每月23日";
                    checkbox-checked: root.all-checked;
                }
                Item {
                    text: "每月24日";
                    checkbox-checked: root.all-checked;
                }
                Item {
                    text: "每月25日";
                    checkbox-checked: root.all-checked;
                }
                Item {
                    text: "每月26日";
                    checkbox-checked: root.all-checked;
                }
                Item {
                    text: "每月27日";
                    checkbox-checked: root.all-checked;
                }
                Item {
                    text: "每月28日";
                    checkbox-checked: root.all-checked;
                }
                Item {
                    text: "每月29日";
                    checkbox-checked: root.all-checked;
                }
                Item {
                    text: "每月30日";
                    checkbox-checked: root.all-checked;
                }
                Item {
                    text: "每月31日";
                    checkbox-checked: root.all-checked;
                }
            }
        }

        CheckBox {
            text: "全与 1 日的时刻相同";
            toggled => {
                root.all-checked = !root.all-checked;
            }
        }

        OkCancel {
            vertical-stretch: 3;

            ok-clicked => { root.on-ok-clicked(); }
            cancel-clicked => { root.on-cancel-clicked(); }
        }
    }
    }
}

