import {
    LineEdit, ComboBox, TabWidget, Button,
    GroupBox, VerticalBox, HorizontalBox, SpinBox,
    TextEdit, CheckBox, GridBox
} from "std-widgets.slint";
import {VerticalDividingLine, HorizontalDividingLine} from "../../../components/ui/dividing_line/dividing_line.slint";
// import {BasicEntries} from "./device_edit_dialogs/.slint";
import {TextSpinBox} from "../../../common/ui/text_spinbox.slint";
import {TextLineEdit} from "../../../common/ui/text_lineedit.slint";
import {TextComboBox} from "../../../common/ui/text_combobox.slint";

import {OkCancel} from "../common/ok_cancel.slint";

Pane := Rectangle {
    TouchArea {
        enabled: true;
    }
}

Item := HorizontalBox {
    property <string> text;

    CheckBox {
        text <=> self.text;
    }

    SpinBox {
        value: 0;
        minimum: 0;
        maximum: 1000;
    }
}

export MonthPlanDialog := Window {
    title: "月计划";

    property<string> timer_desc;

    callback on_ok_clicked;
    callback on_cancel_clicked;

    Pane {
    x: 200px;
    y: 100px;
    width: 600px;
    height: 600px;
    background: white;
    border-width: 2px;
    border-color: grey;
    border-radius: 3px;

    VerticalBox {

        GridBox {
            for ri in 10: Item {
                row: ri;
                col: 0;
            }
            for ri in 10: Item {
                row: ri;
                col: 1;
            }
            for ri in 10: Item {
                row: ri;
                col: 2;
            }
        }

        CheckBox {
            text: "全与 1 日的时刻相同";
        }

        OkCancel {
            vertical-stretch: 1;

            ok-clicked => { root.on-ok-clicked(); }
            cancel-clicked => { root.on-cancel-clicked(); }
        }
    }
    }
}

