import {
    LineEdit, ComboBox, TabWidget, Button,
    GroupBox, VerticalBox, HorizontalBox, SpinBox,
    TextEdit, CheckBox
} from "std-widgets.slint";
import {VerticalDividingLine, HorizontalDividingLine} from "../../../components/ui/dividing_line/dividing_line.slint";
// import {BasicEntries} from "./device_edit_dialogs/.slint";
import {TextSpinBox} from "../../../common/ui/text_spinbox.slint";
import {TextLineEdit} from "../../../common/ui/text_lineedit.slint";
import {TextComboBox} from "../../../common/ui/text_combobox.slint";

Pane := Rectangle {
    TouchArea {
        enabled: true;
    }
}

export SerialPortSettingDialog := Window {
    property<string> timer_desc;

    callback on_ok_clicked;
    callback on_cancel_clicked;

    Pane {
    x: 200px;
    y: 100px;
    width: 600px;
    height: 600px;
    background: white;
    border-width: 2px;
    border-color: grey;
    border-radius: 3px;

    VerticalBox {
        GroupBox {
            vertical-stretch: 2;
            title: "设置";
        }

        HorizontalLayout {
            vertical-stretch: 1;

            padding-right: 30px;
            alignment: end;

            Button {
                text: "确定";
                // width: 80px;
                // height: 30px;

                clicked => {
                    root.on_ok_clicked()
                }
            }

            HorizontalDividingLine{ value: 30px; }

            Button {
                text: "取消";
                // width: 80px;
                // height: 30px;

                clicked => {
                    root.on_cancel_clicked()
                }
            }
        }
    }
    }
}

